window.RAW_WORKBOOK = {
  "sourceFile": "副本独立音乐资料收集表 我们的乐队也可以成为你的生活参考数.xlsx",
  "generatedAt": "2026-06-15",
  "sheets": [
    {
      "name": "说明",
      "rows": [
        [
          "独立音乐资料收集表"
        ],
        [
          "感谢帮忙！这份表用来收集你了解的独立音乐乐队 / 音乐人资料。"
        ],
        [
          "怎么填："
        ],
        [
          "• 带 * 的列尽量填；知道就填，不知道就留空——别猜、别编。"
        ],
        [
          "• 拿不准的写进\"备注\"，或在数字后加问号，如 2005?。"
        ],
        [
          "• 只填你熟悉的部分即可，哪怕只填一两个乐队、几个成员都很有帮助。"
        ],
        [
          "• 越冷门的小乐队越欢迎——正是这些不容易查到的信息最珍贵。"
        ],
        [
          "各标签页说明："
        ],
        [
          "• 乐队 — 乐队基本信息（名字、城市、风格、年份、厂牌等）。"
        ],
        [
          "• 成员 — 谁在哪支乐队、担任什么（同一人在多支乐队就填多行）。"
        ],
        [
          "• 厂牌 — 独立厂牌及其旗下乐队。"
        ],
        [
          "• 场地 — Livehouse / 演出空间（活跃年份、是否全年龄段等）。"
        ],
        [
          "• 合作关系 — 持续性合作（联合发行、互相客串、共用厂牌等）。"
        ],
        [
          "• 共同出现 — 单次具体事件（某场拼盘演出、某次同台）。"
        ],
        [
          "重要提示："
        ],
        [
          "• ID 列（B001/P001/L001 等）用于跨表关联，请尽量填写。"
        ],
        [
          "• 如有艺名 / 个人项目（如本名做乐队、艺名做电子），在\"备注\"里说明。"
        ],
        [
          "• 场地数据暂作参考收集，后续模型扩展时接入。"
        ],
        [
          "• \"合作关系\"记录持续性联系，\"共同出现\"记录单次具体事件，请勿混填。"
        ],
        [
          "本表参考结构源自 Michael Azerrad《Our Band Could Be Your Life》关系网络整理。"
        ]
      ]
    },
    {
      "name": "乐队",
      "rows": [
        [
          "乐队ID *",
          "乐队名 *",
          "英文名 / 别名",
          "所在城市 *",
          "主风格 *",
          "次风格",
          "成立年份",
          "解散年份",
          "是否仍在活动",
          "签约厂牌ID",
          "签约厂牌名",
          "前身乐队ID",
          "前身乐队名",
          "一句话简介",
          "章节来源",
          "备注"
        ],
        [
          "B000",
          "〔示例〕夏日洗剂",
          "Summer Detergent",
          "成都",
          "朋克",
          "车库摇滚",
          "2009",
          "2014",
          "否",
          "L000",
          "某某唱片",
          "",
          "",
          "成都早期车库朋克乐队",
          "",
          "解散年份不确定"
        ],
        [
          "B001",
          "Black Flag",
          "Black Flag",
          "洛杉矶",
          "朋克/硬核",
          "重金属",
          "1976",
          "1986",
          "否",
          "L001",
          "SST Records",
          "",
          "",
          "开创独立乐队全国巡演模式；建立SST发行体系的先驱",
          "第一章"
        ],
        [
          "B002",
          "The Minutemen",
          "The Minutemen",
          "圣佩德罗",
          "后朋克",
          "放克/爵士",
          "1980",
          "1985",
          "否",
          "L001",
          "SST Records",
          "B003",
          "The Reactionaries",
          "jam econo哲学；D. Boon 1985年去世后解散",
          "第二章"
        ],
        [
          "B003",
          "The Reactionaries",
          "The Reactionaries",
          "圣佩德罗",
          "朋克",
          "",
          "1979",
          "1980",
          "否",
          "",
          "",
          "",
          "",
          "Minutemen前身；存续约七个月",
          "第二章"
        ],
        [
          "B004",
          "fIREHOSE",
          "fIREHOSE",
          "圣佩德罗",
          "另类摇滚",
          "后朋克",
          "1986",
          "1994",
          "否",
          "L001",
          "SST Records",
          "B002",
          "The Minutemen",
          "Minutemen解散后由Watt & Hurley组建",
          "第二章",
          "后期签约Columbia Records"
        ],
        [
          "B005",
          "Mission of Burma",
          "Mission of Burma",
          "波士顿",
          "后朋克",
          "实验摇滚",
          "1979",
          "1983",
          "否（2002年重组）",
          "L003",
          "Ace of Hearts Records",
          "",
          "",
          "比基础设施早了十年的\"超前\"乐队；耳鸣导致解散",
          "第三章",
          "2002年重组"
        ],
        [
          "B006",
          "Minor Threat",
          "Minor Threat",
          "华盛顿特区",
          "硬核朋克",
          "straight edge",
          "1980",
          "1983",
          "否",
          "L002",
          "Dischord Records",
          "B008",
          "Teen Idles",
          "straight edge 发源地；两年二十五首歌",
          "第四章"
        ],
        [
          "B007",
          "Fugazi",
          "Fugazi",
          "华盛顿特区",
          "后朋克",
          "数学摇滚",
          "1987",
          "2003",
          "否（暂停）",
          "L002",
          "Dischord Records",
          "",
          "",
          "五美元票价；拒绝一切商业妥协；近两百万张唱片",
          "第十一章"
        ],
        [
          "B008",
          "Teen Idles",
          "Teen Idles",
          "华盛顿特区",
          "硬核朋克",
          "",
          "1979",
          "1980",
          "否",
          "L002",
          "Dischord Records",
          "",
          "",
          "Minor Threat前身；发明手背画X的straight edge视觉符号",
          "第四章"
        ],
        [
          "B009",
          "S.O.A.",
          "State of Alert",
          "华盛顿特区",
          "硬核朋克",
          "",
          "1980",
          "1981",
          "否",
          "",
          "",
          "",
          "",
          "Henry Rollins（后改名Garfield）主唱；D.C.早期硬核",
          "第四章"
        ],
        [
          "B010",
          "Hüsker Dü",
          "Hüsker Dü",
          "圣保罗/明尼阿波利斯",
          "另类摇滚",
          "朋克",
          "1979",
          "1988",
          "否",
          "L001",
          "SST Records",
          "",
          "",
          "首支签约主流的核心独立乐队；Mould vs Hart内部张力",
          "第五章",
          "后签约Warner/Reprise"
        ],
        [
          "B011",
          "The Replacements",
          "The Replacements",
          "明尼阿波利斯",
          "另类摇滚",
          "朋克摇滚",
          "1979",
          "1991",
          "否",
          "L007",
          "Twin/Tone Records",
          "",
          "",
          "自毁美学；Bob Stinson 1995年去世",
          "第六章",
          "后签约Warner/Sire"
        ],
        [
          "B012",
          "Sonic Youth",
          "Sonic Youth",
          "纽约",
          "噪音摇滚",
          "实验摇滚",
          "1981",
          "2011",
          "否",
          "L001",
          "SST Records",
          "",
          "",
          "indie原型乐队；把Nirvana引荐给Geffen",
          "第七章",
          "后签约Geffen/DGC"
        ],
        [
          "B013",
          "Butthole Surfers",
          "Butthole Surfers",
          "德克萨斯/奥斯汀",
          "实验摇滚",
          "迷幻",
          "1981",
          "",
          "是",
          "L004",
          "Touch & Go",
          "",
          "",
          "边界测试者；DIY可承载任何内容的证明",
          "第八章",
          "后期签约Capitol"
        ],
        [
          "B014",
          "Big Black",
          "Big Black",
          "芝加哥",
          "工业摇滚",
          "噪音摇滚",
          "1981",
          "1987",
          "否",
          "L004",
          "Touch & Go",
          "",
          "",
          "1987年全盛期主动解散；工业摇滚蓝图",
          "第九章"
        ],
        [
          "B015",
          "Dinosaur Jr",
          "Dinosaur Jr",
          "阿默斯特",
          "另类摇滚",
          "噪音流行",
          "1984",
          "",
          "是",
          "L008",
          "Homestead Records",
          "B016",
          "Mogo",
          "音量即意义；Mascis用沉默压垮Barlow",
          "第十章",
          "后签约Warner"
        ],
        [
          "B016",
          "Mogo",
          "Mogo",
          "阿默斯特",
          "硬核朋克",
          "",
          "1984",
          "1984",
          "否",
          "",
          "",
          "",
          "",
          "Dinosaur Jr前身；首演后数日即解散",
          "第十章"
        ],
        [
          "B017",
          "Beat Happening",
          "Beat Happening",
          "奥林匹亚",
          "独立流行",
          "朋克",
          "1982",
          "1992",
          "否",
          "L005",
          "K Records",
          "",
          "",
          "\"不会演奏\"作为邀请；twee-pop/riot grrrl的精神起点",
          "第十三章"
        ],
        [
          "B018",
          "Mudhoney",
          "Mudhoney",
          "西雅图",
          "垃圾摇滚",
          "车库摇滚",
          "1988",
          "",
          "是",
          "L006",
          "Sub Pop Records",
          "B019",
          "Green River",
          "\"Touch Me Im Sick\"定义西雅图之声；Sub Pop的注脚",
          "第十二章",
          "后签约Warner/Reprise"
        ],
        [
          "B019",
          "Green River",
          "Green River",
          "西雅图",
          "垃圾摇滚",
          "重金属",
          "1984",
          "1987",
          "否",
          "L006",
          "Sub Pop Records",
          "",
          "",
          "Mudhoney与Pearl Jam的共同前身",
          "第十二章"
        ],
        [
          "B020",
          "Bad Brains",
          "Bad Brains",
          "华盛顿特区",
          "硬核朋克",
          "雷鬼",
          "1977",
          "",
          "是",
          "",
          "",
          "",
          "",
          "MacKaye的精神偶像；H.R.劝说MacKaye重组Minor Threat",
          "第四章"
        ],
        [
          "B021",
          "Youth Brigade",
          "Youth Brigade",
          "华盛顿特区",
          "硬核朋克",
          "",
          "1980",
          "1983",
          "否",
          "",
          "",
          "",
          "",
          "Nathan Strejcek组建；与Minor Threat同行1981年跨州巡演",
          "第四章"
        ],
        [
          "B022",
          "Government Issue",
          "Government Issue",
          "华盛顿特区",
          "硬核朋克",
          "",
          "1980",
          "1989",
          "否",
          "",
          "",
          "",
          "",
          "Brian Baker于Minor Threat第一次解散期间加入",
          "第四章"
        ],
        [
          "B023",
          "Rites of Spring",
          "Rites of Spring",
          "华盛顿特区",
          "情感硬核",
          "",
          "1984",
          "1986",
          "否",
          "L002",
          "Dischord Records",
          "",
          "",
          "Fugazi前身之一；D.C. emo早期代表",
          "第十一章"
        ],
        [
          "B024",
          "Embrace",
          "Embrace",
          "华盛顿特区",
          "后硬核",
          "",
          "1985",
          "1986",
          "否",
          "L002",
          "Dischord Records",
          "",
          "",
          "Minor Threat解散后MacKaye的过渡乐队",
          "第十一章"
        ],
        [
          "B025",
          "TAD",
          "TAD",
          "西雅图",
          "垃圾摇滚",
          "重金属",
          "1988",
          "1999",
          "否",
          "L006",
          "Sub Pop Records",
          "",
          "",
          "Sub Pop早期核心乐队；Pepsi商标诉讼拖累Sub Pop",
          "第十二章"
        ],
        [
          "B026",
          "The Necros",
          "The Necros",
          "俄亥俄州托莱多",
          "硬核朋克",
          "",
          "1979",
          "1987",
          "否",
          "L004",
          "Touch & Go",
          "",
          "",
          "Corey Rusk为贝斯手；与Touch & Go深度关联",
          "第三章/第八章"
        ],
        [
          "B027",
          "Deep Wound",
          "Deep Wound",
          "阿默斯特",
          "硬核朋克",
          "",
          "1982",
          "1984",
          "否",
          "",
          "",
          "",
          "",
          "Mascis与Barlow早期乐队",
          "第十章"
        ],
        [
          "B028",
          "The Coachmen",
          "The Coachmen",
          "纽约",
          "后朋克",
          "",
          "1979",
          "1981",
          "否",
          "",
          "",
          "",
          "",
          "Thurston Moore纽约早期乐队",
          "第七章"
        ]
      ]
    },
    {
      "name": "成员",
      "rows": [
        [
          "记录ID *",
          "乐队ID *",
          "乐队名 *",
          "成员姓名 *",
          "成员ID",
          "艺名/项目名（如有）",
          "担任（可多个） *",
          "是否创始成员",
          "加入年份",
          "离开年份",
          "离开原因",
          "备注"
        ],
        [
          "M000",
          "B000",
          "〔示例〕夏日洗剂",
          "张三",
          "P000",
          "否",
          "主唱",
          "是",
          "2009",
          "2014",
          "乐队解散",
          "也在另一支乐队打鼓"
        ],
        [
          "M001",
          "B001",
          "Black Flag",
          "Greg Ginn",
          "P001",
          "否",
          "吉他",
          "是",
          "1976",
          "1986",
          "乐队解散",
          "SST Records创始人"
        ],
        [
          "M002",
          "B001",
          "Black Flag",
          "Chuck Dukowski",
          "P002",
          "否",
          "贝斯",
          "是",
          "1976",
          "1983",
          "主动离队",
          "离队后主持SST Global Booking"
        ],
        [
          "M003",
          "B001",
          "Black Flag",
          "Henry Rollins",
          "P003",
          "否",
          "主唱",
          "否",
          "1981",
          "1986",
          "乐队解散",
          "前身乐队S.O.A."
        ],
        [
          "M004",
          "B001",
          "Black Flag",
          "Raymond Pettibon",
          "P004",
          "否",
          "视觉艺术",
          "是",
          "1976",
          "1986",
          "乐队解散",
          "Greg Ginn之弟；设计Black Flag logo"
        ],
        [
          "M005",
          "B002",
          "The Minutemen",
          "Mike Watt",
          "P005",
          "否",
          "贝斯/主唱",
          "是",
          "1980",
          "1985",
          "D. Boon去世后解散",
          "New Alliance Records联合创始人"
        ],
        [
          "M006",
          "B002",
          "The Minutemen",
          "D. Boon",
          "P006",
          "否",
          "吉他/主唱",
          "是",
          "1980",
          "1985",
          "交通事故去世",
          "1985年12月23日去世，享年27岁"
        ],
        [
          "M007",
          "B002",
          "The Minutemen",
          "George Hurley",
          "P007",
          "否",
          "鼓手",
          "是",
          "1980",
          "1985",
          "D. Boon去世后解散",
          "后与Red Krayola合作"
        ],
        [
          "M008",
          "B004",
          "fIREHOSE",
          "Mike Watt",
          "P005",
          "否",
          "贝斯",
          "是",
          "1986",
          "1994",
          "乐队解散"
        ],
        [
          "M009",
          "B004",
          "fIREHOSE",
          "George Hurley",
          "P007",
          "否",
          "鼓手",
          "是",
          "1986",
          "1994",
          "乐队解散"
        ],
        [
          "M010",
          "B004",
          "fIREHOSE",
          "Ed Crawford",
          "P008",
          "否",
          "吉他",
          "否",
          "1986",
          "1994",
          "乐队解散",
          "俄亥俄Minutemen乐迷；专程赶来说服Watt"
        ],
        [
          "M011",
          "B006",
          "Minor Threat",
          "Ian MacKaye",
          "P009",
          "否",
          "主唱",
          "是",
          "1980",
          "1983",
          "乐队解散",
          "Dischord Records联合创始人；前身Teen Idles"
        ],
        [
          "M012",
          "B006",
          "Minor Threat",
          "Jeff Nelson",
          "P010",
          "否",
          "鼓手",
          "是",
          "1980",
          "1983",
          "乐队解散",
          "Dischord Records联合创始人"
        ],
        [
          "M013",
          "B006",
          "Minor Threat",
          "Lyle Preslar",
          "P011",
          "否",
          "吉他",
          "是",
          "1980",
          "1983",
          "乐队解散",
          "曾短暂就读西北大学，结识Steve Albini"
        ],
        [
          "M014",
          "B006",
          "Minor Threat",
          "Brian Baker",
          "P012",
          "否",
          "贝斯",
          "是",
          "1980",
          "1983",
          "乐队解散",
          "童年吉他神童"
        ],
        [
          "M015",
          "B008",
          "Teen Idles",
          "Ian MacKaye",
          "P009",
          "否",
          "贝斯",
          "是",
          "1979",
          "1980",
          "乐队解散"
        ],
        [
          "M016",
          "B008",
          "Teen Idles",
          "Jeff Nelson",
          "P010",
          "否",
          "鼓手",
          "是",
          "1979",
          "1980",
          "乐队解散"
        ],
        [
          "M017",
          "B008",
          "Teen Idles",
          "Nathan Strejcek",
          "P013",
          "否",
          "主唱",
          "是",
          "1979",
          "1980",
          "乐队解散",
          "后组建Youth Brigade"
        ],
        [
          "M018",
          "B007",
          "Fugazi",
          "Ian MacKaye",
          "P009",
          "否",
          "吉他/主唱",
          "是",
          "1987",
          "2003",
          "乐队暂停"
        ],
        [
          "M019",
          "B007",
          "Fugazi",
          "Guy Picciotto",
          "P014",
          "否",
          "主唱→吉他/主唱",
          "是",
          "1987",
          "2003",
          "乐队暂停",
          "最初只担任主唱，后加入吉他推动集体创作"
        ],
        [
          "M020",
          "B007",
          "Fugazi",
          "Joe Lally",
          "P015",
          "否",
          "贝斯",
          "是",
          "1987",
          "2003",
          "乐队暂停"
        ],
        [
          "M021",
          "B007",
          "Fugazi",
          "Brendan Canty",
          "P016",
          "否",
          "鼓手",
          "是",
          "1987",
          "2003",
          "乐队暂停",
          "父母为民权运动参与者"
        ],
        [
          "M022",
          "B010",
          "Hüsker Dü",
          "Bob Mould",
          "P017",
          "否",
          "吉他/主唱",
          "是",
          "1979",
          "1988",
          "乐队解散",
          "强硬不妥协；签约后戒酒"
        ],
        [
          "M023",
          "B010",
          "Hüsker Dü",
          "Grant Hart",
          "P018",
          "否",
          "鼓手/主唱",
          "是",
          "1979",
          "1988",
          "乐队解散",
          "海洛因成瘾；1986年查出HIV阳性"
        ],
        [
          "M024",
          "B010",
          "Hüsker Dü",
          "Greg Norton",
          "P019",
          "否",
          "贝斯",
          "是",
          "1979",
          "1988",
          "乐队解散",
          "自称\"温水\"，刻意不介入Mould-Hart争斗"
        ],
        [
          "M025",
          "B011",
          "The Replacements",
          "Paul Westerberg",
          "P020",
          "否",
          "主唱/吉他/词曲",
          "是",
          "1979",
          "1991",
          "乐队解散",
          "天赋极强，以自毁为美学"
        ],
        [
          "M026",
          "B011",
          "The Replacements",
          "Bob Stinson",
          "P021",
          "否",
          "吉他",
          "是",
          "1979",
          "1986",
          "被开除",
          "1995年2月18日去世，享年35岁"
        ],
        [
          "M027",
          "B011",
          "The Replacements",
          "Tommy Stinson",
          "P022",
          "否",
          "贝斯",
          "是",
          "1979",
          "1991",
          "乐队解散",
          "Bob Stinson之弟；加入时年仅13岁"
        ],
        [
          "M028",
          "B011",
          "The Replacements",
          "Chris Mars",
          "P023",
          "否",
          "鼓手",
          "是",
          "1979",
          "1991",
          "乐队解散",
          "乐队里最清醒的观察者"
        ],
        [
          "M029",
          "B012",
          "Sonic Youth",
          "Thurston Moore",
          "P024",
          "否",
          "吉他/主唱",
          "是",
          "1981",
          "2011",
          "乐队解散",
          "关系网络高度自觉；\"Thurston知道这一切的意义，就是通讯\""
        ],
        [
          "M030",
          "B012",
          "Sonic Youth",
          "Kim Gordon",
          "P025",
          "否",
          "贝斯/主唱",
          "是",
          "1981",
          "2011",
          "乐队解散",
          "艺术学位出身；\"直接进入流行文化的形式\""
        ],
        [
          "M031",
          "B012",
          "Sonic Youth",
          "Lee Ranaldo",
          "P026",
          "否",
          "吉他",
          "是",
          "1981",
          "2011",
          "乐队解散",
          "Glenn Branca六重奏核心成员兼音乐副手"
        ],
        [
          "M032",
          "B012",
          "Sonic Youth",
          "Steve Shelley",
          "P027",
          "否",
          "鼓手",
          "否",
          "1985",
          "2011",
          "乐队解散"
        ],
        [
          "M033",
          "B013",
          "Butthole Surfers",
          "Gibby Haynes",
          "P028",
          "否",
          "主唱",
          "是",
          "1981",
          "",
          "",
          "前会计师事务所职员"
        ],
        [
          "M034",
          "B013",
          "Butthole Surfers",
          "Paul Leary",
          "P029",
          "否",
          "吉他",
          "是",
          "1981",
          "",
          "",
          "艺术学院Zappa迷"
        ],
        [
          "M035",
          "B013",
          "Butthole Surfers",
          "King Coffey",
          "P030",
          "否",
          "鼓手",
          "否",
          "1983",
          "",
          "",
          "乐队最清醒的记录者"
        ],
        [
          "M036",
          "B014",
          "Big Black",
          "Steve Albini",
          "P031",
          "否",
          "吉他/主唱",
          "是",
          "1981",
          "1987",
          "乐队主动解散",
          "后成为最重要的独立录音师之一"
        ],
        [
          "M037",
          "B014",
          "Big Black",
          "Santiago Durango",
          "P032",
          "否",
          "吉他",
          "是",
          "1981",
          "1987",
          "乐队主动解散",
          "后进入法学院；曾为Minor Threat做音响"
        ],
        [
          "M038",
          "B014",
          "Big Black",
          "Dave Riley",
          "P033",
          "否",
          "贝斯",
          "否",
          "1984",
          "1987",
          "乐队主动解散",
          "接替Jeff Pezzati；底特律出身"
        ],
        [
          "M039",
          "B015",
          "Dinosaur Jr",
          "J Mascis",
          "P034",
          "否",
          "吉他/主唱",
          "是",
          "1984",
          "",
          "",
          "音量即意义；用沉默作为权力工具"
        ],
        [
          "M040",
          "B015",
          "Dinosaur Jr",
          "Lou Barlow",
          "P035",
          "否",
          "贝斯",
          "是",
          "1984",
          "1989",
          "被开除",
          "被迫唱\"Why dont you like me?\"至咳血；后创立Sebadoh"
        ],
        [
          "M041",
          "B015",
          "Dinosaur Jr",
          "Murph",
          "P036",
          "否",
          "鼓手",
          "是",
          "1984",
          "1993",
          "离队",
          "自称\"嬉皮朋克\""
        ],
        [
          "M042",
          "B017",
          "Beat Happening",
          "Calvin Johnson",
          "P037",
          "否",
          "主唱/吉他",
          "是",
          "1982",
          "1992",
          "乐队解散",
          "K Records创始人；\"青少年精神\"倡导者"
        ],
        [
          "M043",
          "B017",
          "Beat Happening",
          "Heather Lewis",
          "P038",
          "否",
          "主唱/鼓手",
          "是",
          "1982",
          "1992",
          "乐队解散",
          "歌词切近个人经历，演唱时感到脆弱"
        ],
        [
          "M044",
          "B017",
          "Beat Happening",
          "Bret Lunsford",
          "P039",
          "否",
          "吉他",
          "是",
          "1982",
          "1992",
          "乐队解散",
          "毕业后在鱼类加工厂工作，后在书店"
        ],
        [
          "M045",
          "B018",
          "Mudhoney",
          "Mark Arm",
          "P040",
          "否",
          "吉他/主唱",
          "是",
          "1988",
          "",
          "",
          "前Green River成员"
        ],
        [
          "M046",
          "B018",
          "Mudhoney",
          "Steve Turner",
          "P041",
          "否",
          "吉他",
          "是",
          "1988",
          "",
          "",
          "\"我们是一个注脚\"；前Green River成员"
        ],
        [
          "M047",
          "B018",
          "Mudhoney",
          "Matt Lukin",
          "P042",
          "否",
          "贝斯",
          "是",
          "1988",
          "1999",
          "离队",
          "前Melvins成员；来自阿伯丁"
        ],
        [
          "M048",
          "B018",
          "Mudhoney",
          "Dan Peters",
          "P043",
          "否",
          "鼓手",
          "是",
          "1988",
          "",
          "",
          "曾短暂加入Nirvana录制\"Sliver\""
        ],
        [
          "M049",
          "B009",
          "S.O.A.",
          "Henry Rollins",
          "P003",
          "否",
          "主唱",
          "是",
          "1980",
          "1981",
          "加入Black Flag"
        ],
        [
          "M050",
          "B023",
          "Rites of Spring",
          "Guy Picciotto",
          "P014",
          "否",
          "主唱",
          "是",
          "1984",
          "1986",
          "乐队解散"
        ],
        [
          "M051",
          "B023",
          "Rites of Spring",
          "Brendan Canty",
          "P016",
          "否",
          "鼓手",
          "是",
          "1984",
          "1986",
          "乐队解散"
        ],
        [
          "M052",
          "B024",
          "Embrace",
          "Ian MacKaye",
          "P009",
          "否",
          "主唱/吉他",
          "是",
          "1985",
          "1986",
          "乐队解散"
        ]
      ]
    },
    {
      "name": "厂牌",
      "rows": [
        [
          "厂牌ID *",
          "厂牌名 *",
          "英文名",
          "所在城市 *",
          "风格倾向",
          "成立年份",
          "是否仍在运营",
          "创始人",
          "旗下乐队ID（逗号隔开）",
          "旗下乐队名（逗号隔开）",
          "备注"
        ],
        [
          "L000",
          "〔示例〕某某唱片",
          "Some Records",
          "成都",
          "朋克/硬核",
          "2008",
          "否",
          "李四",
          "B000",
          "夏日洗剂",
          "已停止运营？"
        ],
        [
          "L001",
          "SST Records",
          "SST Records",
          "洛杉矶/托伦斯",
          "朋克/另类摇滚",
          "1978",
          "是（名存实亡）",
          "Greg Ginn",
          "B001,B002,B004,B010,B012",
          "Black Flag,Minutemen,fIREHOSE,Hüsker Dü,Sonic Youth",
          "建立了地下发行的基础范本"
        ],
        [
          "L002",
          "Dischord Records",
          "Dischord Records",
          "华盛顿特区",
          "硬核/后朋克",
          "1980",
          "是",
          "Ian MacKaye, Jeff Nelson",
          "B006,B007,B008,B023,B024",
          "Minor Threat,Fugazi,Teen Idles,Rites of Spring,Embrace"
        ],
        [
          "L003",
          "Ace of Hearts Records",
          "Ace of Hearts Records",
          "波士顿",
          "后朋克",
          "1979",
          "否",
          "",
          "B005",
          "Mission of Burma"
        ],
        [
          "L004",
          "Touch & Go Records",
          "Touch & Go Records",
          "芝加哥",
          "朋克/工业/实验",
          "1979",
          "是",
          "Tesco Vee, Corey Rusk",
          "B013,B014,B026",
          "Butthole Surfers,Big Black,The Necros"
        ],
        [
          "L005",
          "K Records",
          "K Records",
          "奥林匹亚",
          "独立流行/twee",
          "1982",
          "是",
          "Calvin Johnson",
          "B017",
          "Beat Happening",
          "座右铭\"International Pop Underground\""
        ],
        [
          "L006",
          "Sub Pop Records",
          "Sub Pop Records",
          "西雅图",
          "垃圾摇滚/另类摇滚",
          "1986",
          "是",
          "Bruce Pavitt, Jonathan Poneman",
          "B018,B019,B025",
          "Mudhoney,Green River,TAD",
          "座右铭\"World Domination\""
        ],
        [
          "L007",
          "Twin/Tone Records",
          "Twin/Tone Records",
          "明尼阿波利斯",
          "另类摇滚/朋克",
          "1977",
          "否",
          "Paul Stark, Peter Jesperson",
          "B011",
          "The Replacements"
        ],
        [
          "L008",
          "Homestead Records",
          "Homestead Records",
          "纽约",
          "另类摇滚/噪音摇滚",
          "1983",
          "否",
          "Gerard Cosloy",
          "B015,B012",
          "Dinosaur Jr,Sonic Youth（早期）",
          "Cosloy离开后逐渐消失"
        ],
        [
          "L009",
          "Reprise/Warner",
          "Reprise Records",
          "洛杉矶",
          "主流（另类摇滚）",
          "1958",
          "是",
          "",
          "B010",
          "Hüsker Dü"
        ],
        [
          "L010",
          "Geffen/DGC",
          "DGC Records",
          "洛杉矶",
          "主流（另类摇滚）",
          "1990",
          "是",
          "",
          "B012",
          "Sonic Youth"
        ],
        [
          "L011",
          "New Alliance Records",
          "New Alliance Records",
          "圣佩德罗",
          "朋克/另类",
          "1980",
          "否",
          "Mike Watt, D. Boon",
          "B002",
          "The Minutemen"
        ],
        [
          "L012",
          "Alternative Tentacles",
          "Alternative Tentacles",
          "旧金山",
          "朋克/硬核",
          "1979",
          "是",
          "Jello Biafra"
        ]
      ]
    },
    {
      "name": "场地",
      "rows": [
        [
          "场地ID *",
          "场地名 *",
          "所在城市 *",
          "活跃起始年份",
          "活跃结束年份",
          "容纳人数（约）",
          "对场景的意义",
          "备注"
        ],
        [
          "V000",
          "〔示例〕小酒馆",
          "成都",
          "1997",
          "",
          "200",
          "成都老牌livehouse，推动了西南独立场景早期发展"
        ],
        [
          "V001",
          "9:30 Club",
          "华盛顿特区",
          "1980",
          "",
          "500",
          "D.C.硬核场景核心演出场地；曾执行全年龄段政策，影响整个D.C.场景人员构成"
        ],
        [
          "V002",
          "Wilson Center",
          "华盛顿特区",
          "1980",
          "1983",
          "300",
          "D.C.早期演出空间，面向全年龄段开放"
        ],
        [
          "V003",
          "Tropicana",
          "奥林匹亚",
          "1984",
          "1985",
          "200",
          "奥林匹亚场景关键孵化地；面向全年龄段；被当地噪音法规关闭"
        ],
        [
          "V004",
          "Union Theatre",
          "圣佩德罗",
          "1982",
          "1985",
          "300",
          "D. Boon租下并运营；演出时间刻意安排得早让工人能准时回家"
        ],
        [
          "V005",
          "CBGB",
          "纽约",
          "1973",
          "2006",
          "否",
          "350",
          "纽约朋克场景圣地；Replacements在此面对一屋子唱片公司高管搞砸演出"
        ],
        [
          "V006",
          "Georgetown Steamplant",
          "西雅图",
          "1980s",
          "",
          "",
          "Big Black最后一场演出地点；直接影响Sub Pop后来的音乐方向"
        ],
        [
          "V007",
          "Maxwell's",
          "霍博肯/新泽西",
          "1978",
          "2013",
          "200",
          "Ira Kaplan（Yo La Tengo）曾在此任音响师；Dinosaur Jr演出地"
        ],
        [
          "V008",
          "Folk City",
          "纽约",
          "1960s",
          "1987",
          "150",
          "Sonic Youth第二次看Dinosaur Jr演出地；Mascis把Moore震到墙上"
        ],
        [
          "V009",
          "O'Banion's",
          "芝加哥",
          "1980s",
          "",
          "",
          "Minor Threat芝加哥演出地；Santiago Durango在此为其做音响"
        ]
      ]
    },
    {
      "name": "合作关系",
      "rows": [
        [
          "记录ID *",
          "实体A ID *",
          "实体A名称 *",
          "实体A类型 *",
          "实体B ID *",
          "实体B名称 *",
          "实体B类型 *",
          "合作形式 *",
          "开始年份",
          "结束年份",
          "资料来源",
          "备注"
        ],
        [
          "C000",
          "B000",
          "〔示例〕夏日洗剂",
          "乐队",
          "B001",
          "别的乐队",
          "乐队",
          "联合发行EP",
          "2012",
          "2012",
          "",
          "两支乐队共同出资压碟"
        ],
        [
          "C001",
          "B001",
          "Black Flag",
          "乐队",
          "B002",
          "The Minutemen",
          "乐队",
          "面包车借用/排练空间共用/SST引荐",
          "1980",
          "1985",
          "第一章/第二章",
          "Minutemen早期借用Black Flag面包车巡演"
        ],
        [
          "C002",
          "B002",
          "The Minutemen",
          "乐队",
          "L011",
          "New Alliance Records",
          "厂牌",
          "联合创立厂牌",
          "1980",
          "1986",
          "第二章",
          "Watt和D. Boon共同创立"
        ],
        [
          "C003",
          "B010",
          "Hüsker Dü",
          "乐队",
          "L011",
          "New Alliance Records",
          "厂牌",
          "发行专辑",
          "1981",
          "1982",
          "第二章",
          "Land Speed Record早期发行"
        ],
        [
          "C004",
          "P001",
          "Greg Ginn",
          "人物",
          "P004",
          "Raymond Pettibon",
          "人物",
          "兄弟/视觉合作",
          "1976",
          "1986",
          "第一章",
          "Pettibon设计Black Flag logo及SST大量封面"
        ],
        [
          "C005",
          "P009",
          "Ian MacKaye",
          "人物",
          "P003",
          "Henry Rollins",
          "人物",
          "场景同伴/早期宿敌后和解",
          "1980",
          "",
          "第一章/第四章",
          "D.C.场景核心人物；早期曾敌对后和解"
        ],
        [
          "C006",
          "P005",
          "Mike Watt",
          "人物",
          "P006",
          "D. Boon",
          "人物",
          "终生挚友/音乐搭档",
          "1972",
          "1985",
          "第二章",
          "青少年时期在公园偶遇，此后合作终身"
        ],
        [
          "C007",
          "B012",
          "Sonic Youth",
          "乐队",
          "B015",
          "Dinosaur Jr",
          "乐队",
          "带其参加首次真正巡演/精神盟友",
          "1986",
          "",
          "第七章/第十章",
          "Sonic Youth带Dinosaur Jr参加1986年巡演"
        ],
        [
          "C008",
          "B012",
          "Sonic Youth",
          "乐队",
          "B018",
          "Mudhoney",
          "乐队",
          "分割单曲/互相推介",
          "1988",
          "1988",
          "第十二章",
          "各翻唱对方一首歌；把Mudhoney推到全国层面"
        ],
        [
          "C009",
          "P024",
          "Thurston Moore",
          "人物",
          "L006",
          "Sub Pop Records",
          "厂牌",
          "信息流通/互相推介",
          "1987",
          "",
          "第十二章",
          "在Sub Pop公告板留便条推荐乐队；长期保持信息流通"
        ],
        [
          "C010",
          "B013",
          "Butthole Surfers",
          "乐队",
          "L004",
          "Touch & Go Records",
          "厂牌",
          "签约发行",
          "1983",
          "1987",
          "第八章",
          "通过Biafra→Rusk→MacKaye磁带传递链条建立"
        ],
        [
          "C011",
          "P031",
          "Steve Albini",
          "人物",
          "B001",
          "Black Flag",
          "乐队",
          "西北大学同期/通过Nate Kato结识",
          "1982",
          "",
          "第四章/第九章",
          "Albini通过Preslar室友Nate Kato进入地下网络"
        ],
        [
          "C012",
          "P032",
          "Santiago Durango",
          "人物",
          "B006",
          "Minor Threat",
          "乐队",
          "演出音响支持",
          "1981",
          "1981",
          "第四章",
          "为Minor Threat在芝加哥做音响"
        ],
        [
          "C013",
          "B007",
          "Fugazi",
          "乐队",
          "L009",
          "Positive Force DC",
          "厂牌/组织",
          "组织本地演出/慈善合作",
          "1987",
          "2003",
          "第十一章",
          "Positive Force组织所有Fugazi本地演出；收益捐给本地组织"
        ],
        [
          "C014",
          "P009",
          "Ian MacKaye",
          "人物",
          "P010",
          "Jeff Nelson",
          "人物",
          "联合创立Dischord Records",
          "1980",
          "",
          "第四章",
          "Dischord Records联合创始人"
        ],
        [
          "C015",
          "B012",
          "Sonic Youth",
          "乐队",
          "L010",
          "Geffen/DGC",
          "厂牌",
          "签约（磁铁乐队策略）",
          "1990",
          "",
          "第七章",
          "Sonic Youth作为文化背书引入Nirvana"
        ],
        [
          "C016",
          "P028",
          "Gibby Haynes",
          "人物",
          "P029",
          "Paul Leary",
          "人物",
          "联合出版地下杂志/联合组建乐队",
          "1980",
          "",
          "第八章",
          "共同出版《Strange V.D.》；共同创立Butthole Surfers"
        ],
        [
          "C017",
          "P037",
          "Calvin Johnson",
          "人物",
          "L005",
          "K Records",
          "厂牌",
          "创立厂牌/核心运营",
          "1982",
          "",
          "第十三章",
          "K Records创始人兼核心人物"
        ],
        [
          "C018",
          "P037",
          "Calvin Johnson",
          "人物",
          "P024",
          "Thurston Moore",
          "人物",
          "音乐网络联系/互相支持",
          "1985",
          "",
          "第十三章",
          "Moore曾在K Records公告板订购唱片"
        ],
        [
          "C019",
          "B006",
          "Minor Threat",
          "乐队",
          "B021",
          "Youth Brigade",
          "乐队",
          "跨州巡演同行",
          "1981",
          "1981",
          "第四章",
          "1981年夏共同参与跨州巡演"
        ],
        [
          "C020",
          "P021",
          "Bob Stinson",
          "人物",
          "P022",
          "Tommy Stinson",
          "人物",
          "兄弟",
          "",
          "",
          "第六章",
          "Bob和Tommy Stinson是亲兄弟"
        ],
        [
          "C021",
          "P009",
          "Ian MacKaye",
          "人物",
          "B020",
          "Bad Brains",
          "乐队",
          "精神影响/H.R.劝说重组Minor Threat",
          "1980",
          "",
          "第四章",
          "MacKaye视H.R.为精神偶像"
        ],
        [
          "C022",
          "P040",
          "Mark Arm",
          "人物",
          "B014",
          "Big Black",
          "乐队",
          "Big Black最后演出台下第一排观众",
          "1987",
          "1987",
          "第九章",
          "此后影响了Sub Pop的音乐方向"
        ],
        [
          "C023",
          "P026",
          "Lee Ranaldo",
          "人物",
          "P044",
          "Glenn Branca",
          "人物",
          "六重奏核心成员/音乐副手",
          "1981",
          "1986",
          "第七章",
          "Branca称其\"比任何人都更理解我的音乐感觉\""
        ],
        [
          "C024",
          "P024",
          "Thurston Moore",
          "人物",
          "P044",
          "Glenn Branca",
          "人物",
          "参与六重奏",
          "1981",
          "1983",
          "第七章"
        ],
        [
          "C025",
          "P025",
          "Kim Gordon",
          "人物",
          "P044",
          "Glenn Branca",
          "人物",
          "通过Branca圈子接触音乐",
          "1981",
          "",
          "第七章"
        ],
        [
          "C026",
          "P028",
          "Gibby Haynes",
          "人物",
          "P030",
          "King Coffey",
          "人物",
          "共同创立Butthole Surfers/长期合作",
          "1981",
          "",
          "第八章"
        ],
        [
          "C027",
          "B010",
          "Hüsker Dü",
          "乐队",
          "L009",
          "Reprise/Warner",
          "厂牌",
          "签约主流（首支）",
          "1986",
          "1988",
          "第五章",
          "首支签约主流的核心独立乐队；给予完全创作控制权"
        ],
        [
          "C028",
          "P030",
          "King Coffey",
          "人物",
          "L004",
          "Touch & Go",
          "厂牌",
          "中间人/信息传递",
          "1983",
          "",
          "第八章"
        ],
        [
          "C029",
          "P045",
          "Jello Biafra",
          "人物",
          "P046",
          "Corey Rusk",
          "人物",
          "磁带传递（Butthole Surfers demo）",
          "1983",
          "1983",
          "第八章",
          "Biafra把Butthole Surfers demo传给Rusk"
        ],
        [
          "C030",
          "P046",
          "Corey Rusk",
          "人物",
          "P009",
          "Ian MacKaye",
          "人物",
          "磁带传递/笔友",
          "1983",
          "",
          "第八章",
          "Rusk把Butthole Surfers磁带转交给借住的MacKaye"
        ]
      ]
    },
    {
      "name": "共同出现",
      "rows": [
        [
          "事件ID *",
          "参与实体ID（逗号隔开） *",
          "参与实体名称 *",
          "时间",
          "场地名",
          "所在城市",
          "事件描述",
          "备注"
        ],
        [
          "E000",
          "B000,B001",
          "〔示例〕夏日洗剂, 别的乐队",
          "2012年夏",
          "小酒馆",
          "成都",
          "一场拼盘演出，约200人到场"
        ],
        [
          "E001",
          "B001,B017",
          "Black Flag, Beat Happening",
          "1984年9月",
          "Tropicana",
          "奥林匹亚",
          "Beat Happening为Black Flag暖场；Rollins起哄Johnson；Johnson用\"你妈妈没教过你礼貌吗\"化解"
        ],
        [
          "E002",
          "B012,B015",
          "Sonic Youth, Dinosaur Jr",
          "1986",
          "Folk City",
          "纽约",
          "Sonic Youth第二次看Dinosaur Jr演出；Mascis第一首歌把Moore震到墙上"
        ],
        [
          "E003",
          "B012,B015,P026",
          "Sonic Youth, Dinosaur Jr, Lee Ranaldo",
          "1986年巡演末场",
          "",
          "",
          "最后一场Ranaldo上台与Dinosaur Jr合唱Neil Young的Cortez the Killer"
        ],
        [
          "E004",
          "B006,B021",
          "Minor Threat, Youth Brigade",
          "1981年夏",
          "",
          "跨州巡演",
          "Minor Threat与Youth Brigade共同参与跨州巡演"
        ],
        [
          "E005",
          "B014,P040",
          "Big Black, Mark Arm",
          "1987",
          "Georgetown Steamplant",
          "西雅图",
          "Big Black最后一场演出；Mark Arm在台下第一排；直接影响Sub Pop音乐方向"
        ],
        [
          "E006",
          "B011",
          "The Replacements",
          "1984前后",
          "CBGB",
          "纽约",
          "Replacements面对一屋子唱片公司高管演奏一场乱糟糟的翻唱秀；Westerberg说\"我们能拿到唱片合同了吗\""
        ],
        [
          "E007",
          "B007",
          "Fugazi",
          "斯波坎某场演出",
          "",
          "斯波坎",
          "Picciotto请全场举手；邀请其他观众上台；乐队下到台下围着暴力舞者演奏"
        ],
        [
          "E008",
          "B005",
          "Mission of Burma",
          "1983年末",
          "Bradford Hotel",
          "波士顿",
          "Mission of Burma正式告别演出"
        ],
        [
          "E009",
          "B017,B012",
          "Beat Happening, Sonic Youth",
          "1991年8月",
          "Fantagraphics仓库",
          "西雅图",
          "International Pop Underground Convention；150人，无舞台，旁边是漫画书箱子"
        ],
        [
          "E010",
          "B007",
          "Fugazi",
          "1980s末",
          "Lorton惩教所",
          "弗吉尼亚",
          "Fugazi在弗吉尼亚州Lorton惩教所演出"
        ]
      ]
    },
    {
      "name": "场景",
      "rows": [
        [
          "场景ID *",
          "场景名 *",
          "场景类型（可多选：本地/跨地域/虚拟） *",
          "地理范围",
          "起始年份",
          "结束年份（仍延续留空）",
          "核心实体ID（逗号隔开）",
          "核心实体名称",
          "场景描述/边界依据 *",
          "备注"
        ],
        [
          "SC000",
          "〔示例〕成都朋克场景 2005-2012",
          "本地",
          "成都",
          "2005",
          "2012",
          "B000,L000",
          "夏日洗剂, 某某唱片",
          "以小酒馆为核心场地，围绕某某唱片旗下乐队形成的本地朋克社群"
        ],
        [
          "SC001",
          "D.C. 硬核场景 1979–1983",
          "本地",
          "华盛顿特区",
          "1979",
          "1983",
          "B006,B008,B009,B020,B021,B022,L002",
          "Minor Threat,Teen Idles,S.O.A.,Bad Brains,Youth Brigade,Government Issue,Dischord",
          "MacKaye/Nelson为核心；Wilson High和Georgetown Day School构成人员基础；9:30 Club和Wilson Center为主要场地；straight edge文化发源地"
        ],
        [
          "SC002",
          "D.C. 后硬核场景 1984–2003",
          "本地",
          "华盛顿特区",
          "1984",
          "",
          "B007,B023,B024,L002",
          "Fugazi,Rites of Spring,Embrace,Dischord",
          "Revolution Summer后的D.C.场景；情感硬核/后硬核；Fugazi将场景建设推至道德极致"
        ],
        [
          "SC003",
          "SST 生态圈 1978–1989",
          "跨地域",
          "洛杉矶/圣佩德罗/明尼阿波利斯/纽约",
          "1978",
          "1989",
          "B001,B002,B004,B010,B012,L001",
          "Black Flag,Minutemen,fIREHOSE,Hüsker Dü,Sonic Youth,SST Records",
          "以SST Records为枢纽的全国独立网络；Global Booking部门支撑全国巡演；跨越多个城市和风格"
        ],
        [
          "SC004",
          "奥林匹亚 K 场景 1982–1992",
          "本地/跨地域",
          "奥林匹亚/国际",
          "1982",
          "",
          "B017,L005",
          "Beat Happening,K Records",
          "Calvin Johnson魅力驱动；非竞争性氛围吸引被硬核排斥的人群（尤其女性）；连接苏格兰/澳大利亚/新西兰同类乐队；riot grrrl运动温床"
        ],
        [
          "SC005",
          "西雅图格朗基场景 1986–1992",
          "本地",
          "西雅图",
          "1986",
          "1992",
          "B018,B019,B025,L006",
          "Mudhoney,Green River,TAD,Sub Pop Records",
          "Sub Pop Records为核心；Charles Peterson视觉语言定义场景形象；Big Black最后演出点燃场景；Nevermind后被主流收割"
        ],
        [
          "SC006",
          "波士顿后朋克场景 1979–1983",
          "本地",
          "波士顿",
          "1979",
          "1983",
          "B005",
          "Mission of Burma",
          "比基础设施早十年的超前场景；Academy Fight Song定义了场景的声音；因成员耳鸣被迫终结"
        ],
        [
          "SC007",
          "芝加哥工业/噪音场景 1981–1987",
          "本地",
          "芝加哥",
          "1981",
          "1987",
          "B014,B026,L004",
          "Big Black,The Necros,Touch & Go Records",
          "Touch & Go Records为枢纽；Albini\"价值来自内部\"哲学；1987年Big Black主动解散标志场景顶峰"
        ],
        [
          "SC008",
          "明尼阿波利斯另类摇滚场景 1979–1991",
          "本地",
          "明尼阿波利斯/圣保罗",
          "1979",
          "1991",
          "B010,B011,L007",
          "Hüsker Dü,The Replacements,Twin/Tone Records",
          "Hüsker Dü与Replacements同城平行；前者严肃有野心，后者放任自毁；两支乐队先后签约主流标志场景终结"
        ],
        [
          "SC009",
          "K 国际流行地下网络 1982–",
          "跨地域",
          "奥林匹亚/苏格兰/澳大利亚/新西兰",
          "1982",
          "",
          "L005,B017",
          "K Records,Beat Happening",
          "水平网络连接各地同类乐队；无中心，无层级；CB无线电式\"烟雾信号\"通讯；与Sub Pop\"世界统治\"形成鲜明对比",
          "跨地域场景，持续至今"
        ],
        [
          "SC010",
          "纽约艺术/噪音场景 1981–1990",
          "本地",
          "纽约下东区",
          "1981",
          "1990",
          "B012,B028",
          "Sonic Youth,The Coachmen",
          "Glenn Branca/no wave/Fluxus为文化背景；艺术世界与摇滚的交汇；Sonic Youth以SST为跳板跃出纽约局限"
        ]
      ]
    }
  ]
};
